create view pooling_cars as (
select model_name,registration_no,capacity,pickup_location,drop_location,start_time,end_time,cost_perday,latefee_perday
from booking natural join car natural join car_category 
where pooling_option = 1 and now()::date<start_time and booking.cancelled_status = 'No' 
and 
capacity >= 1 + (select get_count_bookingid(booking.booking_id))
);

/* ------------------------------------------------------------------------------------------------------------------------ */